version: "3.9"

services:
  frontend:
    build: frontend
    container_name: frontend 
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build: backend 
    container_name: backend 
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:
